table _Measures
	lineageTag: 12345678-90ab-cdef-1234-567890abcdef

	measure Q1_Cramped_Count = CALCULATE(COUNTROWS('Fact_Listings'), 'Fact_Listings'[Is_Overcrowded] = TRUE)
		formatString: #,0
		displayFolder: Q1 - Nhồi nhét công năng
		lineageTag: q1-0001-0000-0000-000000000001

	measure Q1_Total_With_Data =
			CALCULATE(
			    COUNTROWS('Fact_Listings'),
			    NOT(ISBLANK('Fact_Listings'[Diện tích])),
			    NOT(ISBLANK('Fact_Listings'[Số phòng ngủ]))
			)
		formatString: #,0
		displayFolder: Q1 - Nhồi nhét công năng
		lineageTag: q1-0001-0000-0000-000000000002

	measure Q1_Cramped_Pct = DIVIDE([Q1_Cramped_Count], [Q1_Total_With_Data], 0)
		formatString: 0.0%
		displayFolder: Q1 - Nhồi nhét công năng
		lineageTag: q1-0001-0000-0000-000000000003

	measure Q1_Avg_Bedroom_Density =
			AVERAGEX(
			    FILTER(
			        'Fact_Listings',
			        NOT(ISBLANK('Fact_Listings'[Diện tích])) && 'Fact_Listings'[Diện tích] > 0
			    ),
			    DIVIDE('Fact_Listings'[Số phòng ngủ], 'Fact_Listings'[Diện tích])
			)
		formatString: 0.000
		displayFolder: Q1 - Nhồi nhét công năng
		lineageTag: q1-0001-0000-0000-000000000004

	measure Q2_Bath_Bed_Ratio =
			DIVIDE(
			    SUM('Fact_Listings'[Số phòng tắm, vệ sinh]),
			    SUM('Fact_Listings'[Số phòng ngủ]),
			    0
			)
		formatString: 0.00
		displayFolder: Q2 - Tỷ lệ WC/Phòng ngủ
		lineageTag: q2-0002-0000-0000-000000000001

	measure Q2_Anomaly_Ratio_Count =
			CALCULATE(
			    COUNTROWS('Fact_Listings'),
			    'Fact_Listings'[Số phòng tắm, vệ sinh] > 'Fact_Listings'[Số phòng ngủ] * 2
			)
		formatString: #,0
		displayFolder: Q2 - Tỷ lệ WC/Phòng ngủ
		lineageTag: q2-0002-0000-0000-000000000002

	measure Q3_Fire_Risk_Count = CALCULATE(COUNTROWS('Fact_Listings'), 'Fact_Listings'[Is_Fire_Risk] = TRUE)
		formatString: #,0
		displayFolder: Q3 - Rủi ro PCCC
		lineageTag: q3-0003-0000-0000-000000000001

	measure Q3_Fire_Risk_Pct = DIVIDE([Q3_Fire_Risk_Count], COUNTROWS('Fact_Listings'), 0)
		formatString: 0.0%
		displayFolder: Q3 - Rủi ro PCCC
		lineageTag: q3-0003-0000-0000-000000000002

	measure Q3_Avg_Floors_FireRisk = CALCULATE(AVERAGE('Fact_Listings'[Số tầng]), 'Fact_Listings'[Is_Fire_Risk] = TRUE)
		formatString: 0.0
		displayFolder: Q3 - Rủi ro PCCC
		lineageTag: q3-0003-0000-0000-000000000003

	measure Q3_Avg_Road_FireRisk = CALCULATE(AVERAGE('Fact_Listings'[Đường vào]), 'Fact_Listings'[Is_Fire_Risk] = TRUE)
		formatString: 0.00
		displayFolder: Q3 - Rủi ro PCCC
		lineageTag: q3-0003-0000-0000-000000000004

	measure Q4_LargeBareShell_Count =
			CALCULATE(
			    COUNTROWS('Fact_Listings'),
			    'Fact_Listings'[Diện tích] > 100,
			    'Fact_Listings'[Số tầng] >= 2,
			    'Dim_Property_Details'[Nội thất] IN {"Không nội thất", "Thô"}
			)
		formatString: #,0
		displayFolder: Q4 - Bare Shell Discount
		lineageTag: q4-0004-0000-0000-000000000001

	measure Q4_AvgPrice_LargeBare =
			CALCULATE(
			    AVERAGE('Fact_Listings'[Đơn giá]),
			    'Fact_Listings'[Diện tích] > 100,
			    'Dim_Property_Details'[Nội thất] IN {"Không nội thất", "Thô"}
			)
		formatString: #,0.00
		displayFolder: Q4 - Bare Shell Discount
		lineageTag: q4-0004-0000-0000-000000000002

	measure Q4_AvgPrice_FullFurniture =
			CALCULATE(
			    AVERAGE('Fact_Listings'[Đơn giá]),
			    'Fact_Listings'[Diện tích] > 100,
			    'Dim_Property_Details'[Nội thất] IN {"Đầy đủ", "Cao cấp"}
			)
		formatString: #,0.00
		displayFolder: Q4 - Bare Shell Discount
		lineageTag: q4-0004-0000-0000-000000000003

	measure Q4_BareShell_Discount_Pct =
			DIVIDE(
			    [Q4_AvgPrice_FullFurniture] - [Q4_AvgPrice_LargeBare],
			    [Q4_AvgPrice_FullFurniture],
			    0
			)
		formatString: 0.0%
		displayFolder: Q4 - Bare Shell Discount
		lineageTag: q4-0004-0000-0000-000000000004

	column _Measures
		dataType: string
		lineageTag: e27efe27-caf1-421e-8db3-1f3365ea355e
		summarizeBy: none
		sourceColumn: _Measures

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source = {{"Measure", "Value"}, {"_Measures", 1}}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TableType = DefaultMeasureTable

