table _Measures
	lineageTag: 12345678-90ab-cdef-1234-567890abcdef

	measure 'Column Color' =
			
			VAR CurrentPrice = MAX('Fact_Listings'[Khoảng đơn giá/m²])
			VAR Threshold = [Ngưỡng rẻ bất thường]
			RETURN
			IF(CurrentPrice < Threshold, "#D55E00", "#D9D9D9")
		lineageTag: c1d25dbe-d424-4e5d-a452-452d1c5e9f21

	measure 'Màu Đỉnh Và Trung Bình' = ```
			
			// 1. Xác định giới hạn dải giá của cột hiện tại đang được vẽ
			VAR CurrentMin = MIN('Fact_Listings'[Giá bán (tỷ đồng)])
			VAR CurrentMax = MAX('Fact_Listings'[Giá bán (tỷ đồng)])
			
			// 2. Cố định giá trị Đỉnh TOÀN CỤC (gỡ bỏ màng lọc của trục X bằng cách quét cả bảng)
			VAR PeakPrice = CALCULATE(
			    VALUE([Vùng giá có nhiều tin nhất]),
			    ALLSELECTED('Fact_Listings')
			)
			
			// 3. Cố định giá trị Trung bình TOÀN CỤC
			VAR AvgPrice = CALCULATE(
			    AVERAGE('Fact_Listings'[Giá bán (tỷ đồng)]), 
			    ALLSELECTED('Fact_Listings')
			)
			
			VAR Radius = 2
			
			// 4. Kiểm tra điều kiện và tô màu
			RETURN
			IF(
			    ISBLANK(CurrentMin), // Thêm bẫy lỗi
			    BLANK(),
			    IF(
			        (CurrentMax >= PeakPrice - Radius && CurrentMax <= PeakPrice + Radius) || 
			        (AvgPrice >= CurrentMin && AvgPrice <= CurrentMax),
			        "#2E5A88", // Màu xanh đậm (Highlight)
			        "#D9D9D9"  // Màu xám trung tính (Neutral)
			    )
			)
			```
		lineageTag: 54784b5d-1a10-4e49-b8a1-f2911bf2971e

	measure 'Màu Bong Bóng Scatter' = ```
			
			// Lấy giá trị Đơn giá của điểm dữ liệu hiện tại
			VAR CurrentPrice = AVERAGE('Fact_Listings'[Đơn giá]) 
			
			// Áp dụng quy tắc màu sắc
			RETURN
			IF(
			    CurrentPrice < [Ngưỡng rẻ bất thường],
			    "#D55E00", // Cam đậm cho điểm có đơn giá < 44.20
			    "#D3D3D3"  // Xám nhạt cho toàn bộ các điểm còn lại
			)
			```
		lineageTag: 6ca9c5cf-e4c4-4d79-8ded-a02b24620bfb

	measure Avg_PricePerM2 =
			AVERAGEX(
				FILTER(
					'Fact_Listings',
					NOT(ISBLANK('Fact_Listings'[Diện tích])) && 'Fact_Listings'[Diện tích] > 0
				),
				DIVIDE('Fact_Listings'[Đơn giá], 'Fact_Listings'[Diện tích], BLANK())
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b476cf2a-0bfb-4115-94ce-4169fd9250d8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure MedianPrice_Tho =
			
			CALCULATE(
			    MEDIAN('Fact_Listings'[Đơn giá]),
			    'Dim_Property_Details'[Nội thất] = "Thô"
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5f1cf280-80fe-4f6d-bd81-0f652b134b30

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure MedianPrice_KhongNoiThat =
			
			CALCULATE(
			    MEDIAN('Fact_Listings'[Đơn giá]),
			    'Dim_Property_Details'[Nội thất] = "Không nội thất"
			)
		formatString: 0.00
		lineageTag: 85843d36-1d65-479c-b224-733b5a48228c

	measure MedianPrice_PhapLyYeuHemNho =
			
			CALCULATE(
			    MEDIAN('Fact_Listings'[Đơn giá]),
			    'Fact_Listings'[Nhom_Chat_Luong_Thocu] = "Pháp lý yếu + Hẻm nhỏ"
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e2db5c5e-b0bc-4b80-8fb1-550f3b07c597

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Ty_Le_Nhoi_Nhet =
			
			DIVIDE(
			    CALCULATE(COUNT('Fact_Listings'[Product_SKey]), 'Fact_Listings'[Diện tích] <= 40, 'Fact_Listings'[Số phòng ngủ] >= 3),
			    COUNT('Fact_Listings'[Product_SKey]),
			    0
			)
		lineageTag: b20f6943-b5e2-4a1e-b1b8-e1a106c109b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _Measures = m
		mode: import
		source =
			let
				measuresList = {{"Measure", "Value"}, {"_Measures", 1}},
				measuresTable = Table.FromRows(measuresList, {"Measure", "_Measures"}),
				#"Removed Columns" = Table.RemoveColumns(measuresTable,{"_Measures"})
			in
				#"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation TableType = DefaultMeasureTable

