table batdongsan_real_estate_cleaned
	lineageTag: e5169c80-e8b3-46bc-bb6e-23f5192fc8c1

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: a04ecd1f-c5c0-40b9-82dc-bcfad1d7a00d
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: a9b3bebe-6998-4d84-b35b-01f0e8bd5b52
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 3a7e8d7d-fb11-43cd-96e4-1a83e5f55599
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 2881c471-798a-40fd-a2c4-a72b6a5ca65d
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column district
		dataType: string
		lineageTag: 34ba44b3-d826-4ba8-92ec-be0622292c22
		summarizeBy: none
		sourceColumn: district

		annotation SummarizationSetBy = Automatic

	column ward
		dataType: string
		lineageTag: 9108250c-66a4-4624-aab0-e4eafb1e8f94
		summarizeBy: none
		sourceColumn: ward

		annotation SummarizationSetBy = Automatic

	column street
		dataType: string
		lineageTag: 552b8a57-134e-4d68-b6eb-b9f03a914c0f
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = Automatic

	column full_address
		dataType: string
		lineageTag: db26e36e-5ae1-4527-bddc-18e4b54c8338
		summarizeBy: none
		sourceColumn: full_address

		annotation SummarizationSetBy = Automatic

	column price_total
		dataType: int64
		formatString: 0
		lineageTag: 6b8f4ee9-4545-43a5-babf-515e472bd506
		summarizeBy: sum
		sourceColumn: price_total

		annotation SummarizationSetBy = Automatic

	column price_per_m2
		dataType: double
		lineageTag: 75f75f2a-e21a-41a8-91ad-3024e3c1f87c
		summarizeBy: sum
		sourceColumn: price_per_m2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column area
		dataType: double
		lineageTag: 970d9577-39bc-4120-9cc4-17766c79f8e6
		summarizeBy: sum
		sourceColumn: area

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column frontage
		dataType: double
		lineageTag: 4c12ffc9-7bce-42d4-9c77-57ec67c193de
		summarizeBy: sum
		sourceColumn: frontage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column road_width
		dataType: double
		lineageTag: 88ac8abd-9b27-4d0e-ab35-17c6b8b74845
		summarizeBy: sum
		sourceColumn: road_width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bedrooms
		dataType: int64
		formatString: 0
		lineageTag: e3fe6567-a055-4fbc-9810-0698f5aa311c
		summarizeBy: sum
		sourceColumn: bedrooms

		annotation SummarizationSetBy = Automatic

	column bathrooms
		dataType: int64
		formatString: 0
		lineageTag: a4e483b1-1e92-4683-99de-c388d47d9d26
		summarizeBy: sum
		sourceColumn: bathrooms

		annotation SummarizationSetBy = Automatic

	column floors
		dataType: int64
		formatString: 0
		lineageTag: a4d6b926-761b-4f11-b581-99b31dfc1da3
		summarizeBy: sum
		sourceColumn: floors

		annotation SummarizationSetBy = Automatic

	column direction
		dataType: string
		lineageTag: 4aa7b3c3-7559-49c6-830b-b23a776ae216
		summarizeBy: none
		sourceColumn: direction

		annotation SummarizationSetBy = Automatic

	column interior
		dataType: string
		lineageTag: d21197cf-f949-4139-b00b-e08c226392c4
		summarizeBy: none
		sourceColumn: interior

		annotation SummarizationSetBy = Automatic

	column legal_status
		dataType: string
		lineageTag: 60602e00-4ef0-4a7b-b130-f0cd180e8276
		summarizeBy: none
		sourceColumn: legal_status

		annotation SummarizationSetBy = Automatic

	column post_rank
		dataType: string
		lineageTag: c3fac931-ac4a-432b-a913-66744dd25785
		summarizeBy: none
		sourceColumn: post_rank

		annotation SummarizationSetBy = Automatic

	column price_trend_1y
		dataType: double
		lineageTag: 93be097c-3419-41dd-8bc5-f2716c0725c7
		summarizeBy: sum
		sourceColumn: price_trend_1y

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column has_elevator
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ca81873c-d9e4-4621-9e98-8f47a0d672ba
		summarizeBy: none
		sourceColumn: has_elevator

		annotation SummarizationSetBy = Automatic

	column near_park
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e4ff6794-e9d1-4ad7-82d1-5df826a48327
		summarizeBy: none
		sourceColumn: near_park

		annotation SummarizationSetBy = Automatic

	column is_frontage_road
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5b23e857-0655-48a9-b41c-d3d8b8e4b4b3
		summarizeBy: none
		sourceColumn: is_frontage_road

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: df1a0219-492b-492c-a8a4-5383eb9599ac
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column posted_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8241dfa-0066-4fe7-8572-d1271ad78db9
		summarizeBy: none
		sourceColumn: posted_date

		variation Variation
			isDefault
			relationship: 90c14991-8c63-411d-8c24-68225202675b
			defaultHierarchy: LocalDateTable_2e1fcaea-258d-4ce7-9027-3dbd85f47cf9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column expiry_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 062b4eba-9286-43ee-a218-15361d350f8a
		summarizeBy: none
		sourceColumn: expiry_date

		variation Variation
			isDefault
			relationship: 908ff486-1971-4ae3-9653-704b8a76e59f
			defaultHierarchy: LocalDateTable_efb00036-6bdf-4ec2-98bf-e40af2140a00.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition batdongsan_real_estate_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Admin\Documents\DataVisualisation_Final\Dataset\batdongsan_real_estate_cleaned.csv"),[Delimiter=",", Columns=27, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"title", type text}, {"url", type text}, {"city", type text}, {"district", type text}, {"ward", type text}, {"street", type text}, {"full_address", type text}, {"price_total", Int64.Type}, {"price_per_m2", type number}, {"area", type number}, {"frontage", type number}, {"road_width", type number}, {"bedrooms", Int64.Type}, {"bathrooms", Int64.Type}, {"floors", Int64.Type}, {"direction", type text}, {"interior", type text}, {"legal_status", type text}, {"post_rank", type text}, {"price_trend_1y", type number}, {"has_elevator", type logical}, {"near_park", type logical}, {"is_frontage_road", type logical}, {"description", type text}, {"posted_date", type date}, {"expiry_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

