table Dim_Property_Details
	lineageTag: 61bc28d9-a4c7-4ae8-86cc-9a61bd60bf63

	column Status_SKey
		dataType: int64
		formatString: 0
		lineageTag: 1f9dac49-3a7f-4374-8ce6-e0a39c21d08b
		summarizeBy: none
		sourceColumn: Status_SKey

		annotation SummarizationSetBy = Automatic

	column 'Hướng nhà'
		dataType: string
		lineageTag: 9b08e4e5-810c-4218-b0a5-2bdab76a11ef
		summarizeBy: none
		sourceColumn: Hướng nhà

		annotation SummarizationSetBy = Automatic

	column 'Nội thất'
		dataType: string
		lineageTag: 78e9ac28-02b3-426a-acc3-9e8e0240e4cf
		summarizeBy: none
		sourceColumn: Nội thất

		annotation SummarizationSetBy = Automatic

	column 'Pháp lý'
		dataType: string
		lineageTag: 90dfb8b3-c463-4ed8-823f-c3f909fe70bd
		summarizeBy: none
		sourceColumn: Pháp lý

		annotation SummarizationSetBy = Automatic

	column 'Loại tin'
		dataType: string
		lineageTag: 78d90fc4-4b30-4b63-9f31-4cf7d9091e21
		summarizeBy: none
		sourceColumn: Loại tin

		annotation SummarizationSetBy = Automatic

	column 'Pháp lý Chuẩn hóa'
		dataType: string
		lineageTag: 3d070318-d38b-4793-9a40-e63c139312bf
		summarizeBy: none
		sourceColumn: Pháp lý Chuẩn hóa

		annotation SummarizationSetBy = Automatic

	partition Dim_Property_Details = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Hướng nhà", "Nội thất", "Pháp lý", "Pháp lý Chuẩn hóa", "Loại tin"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Status_SKey", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

