table Dim_Features
	lineageTag: c1711940-a3e9-4ffb-9e8d-6997ce58bed5

	column Feature_SKey
		dataType: int64
		formatString: 0
		lineageTag: 3d3bdc49-5fa0-4e1d-b2ea-4360f496aad9
		summarizeBy: none
		sourceColumn: Feature_SKey

		annotation SummarizationSetBy = Automatic

	column 'Có thang máy'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ccaa989e-a742-4176-a696-ead7c73bf4b5
		summarizeBy: none
		sourceColumn: Có thang máy

		annotation SummarizationSetBy = Automatic

	column 'Gần công viên'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cdfa54de-a02c-4dca-ac7e-fc299c21ba0a
		summarizeBy: none
		sourceColumn: Gần công viên

		annotation SummarizationSetBy = Automatic

	column 'Có dấu hiệu bán gấp'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2f053864-4652-4c88-9f36-008f4dca8a8d
		summarizeBy: none
		sourceColumn: Có dấu hiệu bán gấp

		annotation SummarizationSetBy = Automatic

	column 'Có từ khóa marketing'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b4f58342-d7ba-4c72-b551-233730f4e2a8
		summarizeBy: none
		sourceColumn: Có từ khóa marketing

		annotation SummarizationSetBy = Automatic

	column 'Có từ khóa dòng tiền'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 947d6fa7-32f8-4f28-91f5-8f85db09fb55
		summarizeBy: none
		sourceColumn: Có từ khóa dòng tiền

		annotation SummarizationSetBy = Automatic

	column 'Có dấu hiệu pháp lý yếu'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d4e31f5d-6454-44f0-81ac-cfb0f5ceb905
		summarizeBy: none
		sourceColumn: Có dấu hiệu pháp lý yếu

		annotation SummarizationSetBy = Automatic

	partition Dim_Features = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Có thang máy", "Gần công viên", "Có dấu hiệu bán gấp", "Có từ khóa marketing", "Có từ khóa dòng tiền", "Có dấu hiệu pháp lý yếu"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Feature_SKey", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

