table Dim_Location
	lineageTag: 8450f79a-f010-4eea-adfa-84437913e865

	column city
		dataType: string
		lineageTag: 8e4f7b36-4e2c-4e62-b701-d9c53319fd44
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column district
		dataType: string
		lineageTag: fed1137a-1218-4f7e-8432-9145043db24a
		summarizeBy: none
		sourceColumn: district

		annotation SummarizationSetBy = Automatic

	column ward
		dataType: string
		lineageTag: 4b00cf5b-35b0-4faa-b3a3-4725d0d0c462
		summarizeBy: none
		sourceColumn: ward

		annotation SummarizationSetBy = Automatic

	column street
		dataType: string
		lineageTag: ec7fd1b8-c5bf-498a-a2f6-9aeee43e28d3
		summarizeBy: none
		sourceColumn: street

		annotation SummarizationSetBy = Automatic

	column full_address
		dataType: string
		lineageTag: 498a6aff-7ce4-482b-8a5e-026f1f5b093e
		summarizeBy: none
		sourceColumn: full_address

		annotation SummarizationSetBy = Automatic

	column Location_SKey
		dataType: int64
		formatString: 0
		lineageTag: 6d24569c-b7fd-425f-9cd4-ace90efe98e1
		summarizeBy: none
		sourceColumn: Location_SKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Location = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"city", "district", "ward", "street", "full_address"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"city", "district", "ward", "street", "full_address"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Location_SKey", 1, 1, Int64.Type),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Index",{{"Location_SKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

