table Dim_Features
	lineageTag: c1711940-a3e9-4ffb-9e8d-6997ce58bed5

	column 'Có thang máy'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2d9ecf48-0337-451b-a07e-b6de031bb04f
		summarizeBy: none
		sourceColumn: Có thang máy

		annotation SummarizationSetBy = Automatic

	column 'Gần công viên'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0fc2e92d-1e68-47c3-8ed2-b66f3ec7ce88
		summarizeBy: none
		sourceColumn: Gần công viên

		annotation SummarizationSetBy = Automatic

	column 'Nhà mặt tiền'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 94d23bb6-929d-4106-8297-ce7c516cdb53
		summarizeBy: none
		sourceColumn: Nhà mặt tiền

		annotation SummarizationSetBy = Automatic

	column Feature_SKey
		dataType: int64
		formatString: 0
		lineageTag: 3d3bdc49-5fa0-4e1d-b2ea-4360f496aad9
		summarizeBy: none
		sourceColumn: Feature_SKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Features = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"has_elevator", "near_park", "is_frontage_road"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Feature_SKey", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"has_elevator", "Có thang máy"}, {"near_park", "Gần công viên"}, {"is_frontage_road", "Nhà mặt tiền"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

