table Dim_Location
	lineageTag: 8450f79a-f010-4eea-adfa-84437913e865

	column Location_SKey
		dataType: int64
		formatString: 0
		lineageTag: 6d24569c-b7fd-425f-9cd4-ace90efe98e1
		summarizeBy: none
		sourceColumn: Location_SKey

		annotation SummarizationSetBy = Automatic

	column 'Thành phố'
		dataType: string
		lineageTag: c7f6b949-ac4e-4308-ba29-0ae7839b59da
		summarizeBy: none
		sourceColumn: Thành phố

		annotation SummarizationSetBy = Automatic

	column Quận
		dataType: string
		lineageTag: 07fd0a83-3d5d-48cf-98ba-8eafbf88da5a
		summarizeBy: none
		sourceColumn: Quận

		annotation SummarizationSetBy = Automatic

	column Phường
		dataType: string
		lineageTag: c4a3b36e-814c-444d-8bcc-6f449578fb0f
		summarizeBy: none
		sourceColumn: Phường

		annotation SummarizationSetBy = Automatic

	column Đường
		dataType: string
		lineageTag: 7d23038a-6ae8-452d-83e8-d676368d878e
		summarizeBy: none
		sourceColumn: Đường

		annotation SummarizationSetBy = Automatic

	column 'Địa chỉ'
		dataType: string
		lineageTag: 3e94a557-f03f-4e64-9ce6-287ccd2a0907
		summarizeBy: none
		sourceColumn: Địa chỉ

		annotation SummarizationSetBy = Automatic

	partition Dim_Location = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Location_SKey", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

