table Dim_Features
	lineageTag: c1711940-a3e9-4ffb-9e8d-6997ce58bed5

	column Feature_SKey
		dataType: int64
		formatString: 0
		lineageTag: 3d3bdc49-5fa0-4e1d-b2ea-4360f496aad9
		summarizeBy: none
		sourceColumn: Feature_SKey

		annotation SummarizationSetBy = Automatic

	column 'Có thang máy'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ccaa989e-a742-4176-a696-ead7c73bf4b5
		summarizeBy: none
		sourceColumn: Có thang máy

		annotation SummarizationSetBy = Automatic

	column 'Gần công viên'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cdfa54de-a02c-4dca-ac7e-fc299c21ba0a
		summarizeBy: none
		sourceColumn: Gần công viên

		annotation SummarizationSetBy = Automatic

	partition Dim_Features = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Có thang máy", "Gần công viên"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Feature_SKey", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

