table Fact_Listings
	lineageTag: 6dbf4d8b-6450-49d9-a197-1bfe46312350

	column expiry_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7d6de7f-603e-48ac-8f26-fdce5fac2193
		summarizeBy: none
		sourceColumn: expiry_date

		variation Variation
			isDefault
			relationship: c1dda36e-3c20-4b50-8efd-d85df39eb2b3
			defaultHierarchy: LocalDateTable_4275abd7-7c0a-44cc-993a-521f5c6f11de.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Location_SKey
		dataType: int64
		formatString: 0
		lineageTag: 8eb85d28-0efa-49e7-9036-739ea7fcbf77
		summarizeBy: none
		sourceColumn: Location_SKey

		annotation SummarizationSetBy = Automatic

	column Feature_SKey
		dataType: int64
		formatString: 0
		lineageTag: 3c399081-33a6-4d15-b65d-c54843c31f0b
		summarizeBy: none
		sourceColumn: Feature_SKey

		annotation SummarizationSetBy = Automatic

	column Status_SKey
		dataType: int64
		formatString: 0
		lineageTag: 95d8cd6d-d25e-4a4c-bf40-0e9993a3c007
		summarizeBy: none
		sourceColumn: Status_SKey

		annotation SummarizationSetBy = Automatic

	column Product_SKey
		dataType: int64
		formatString: 0
		lineageTag: 41b238fa-ed81-41e6-9589-8f0722c103cd
		summarizeBy: none
		sourceColumn: Product_SKey

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 3fc458c6-ec92-4734-8de1-082769bd49d6
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 03d37c6c-a51f-4265-973a-48293f7041c1
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column 'Bất động sản'
		dataType: string
		lineageTag: 9654a485-fc32-42cd-a593-51d022d1b9cc
		summarizeBy: none
		sourceColumn: Bất động sản

		annotation SummarizationSetBy = Automatic

	column 'Thành phố'
		dataType: string
		lineageTag: b58a4754-1087-430f-9f43-6241b9fc23e4
		summarizeBy: none
		sourceColumn: Thành phố

		annotation SummarizationSetBy = Automatic

	column Quận
		dataType: string
		lineageTag: e4d0c349-21ba-4440-ba7d-43bd48ffd3eb
		summarizeBy: none
		sourceColumn: Quận

		annotation SummarizationSetBy = Automatic

	column Phường
		dataType: string
		lineageTag: a5a62351-6216-45ee-9f43-6cdb1eb17874
		summarizeBy: none
		sourceColumn: Phường

		annotation SummarizationSetBy = Automatic

	column Đường
		dataType: string
		lineageTag: 03fd9d21-4509-4598-8cc1-346d9a03f45c
		summarizeBy: none
		sourceColumn: Đường

		annotation SummarizationSetBy = Automatic

	column 'Địa chỉ'
		dataType: string
		lineageTag: 06fd8b0c-2fb8-41aa-bcdd-4e049754b473
		summarizeBy: none
		sourceColumn: Địa chỉ

		annotation SummarizationSetBy = Automatic

	column 'Khoảng giá'
		dataType: int64
		formatString: 0
		lineageTag: 10ba38ee-e25e-4078-bc51-e723929c7cb8
		summarizeBy: sum
		sourceColumn: Khoảng giá

		annotation SummarizationSetBy = Automatic

	column 'Diện tích'
		dataType: double
		lineageTag: 5a749730-4dad-4b19-a63e-d2aa2babe48f
		summarizeBy: sum
		sourceColumn: Diện tích

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mặt tiền'
		dataType: double
		lineageTag: cb21897e-4a1d-40f4-a9cd-77406d0fefa4
		summarizeBy: sum
		sourceColumn: Mặt tiền

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Đường vào'
		dataType: double
		lineageTag: f1509322-b72a-4d5f-bf61-c8c0c3ea661b
		summarizeBy: sum
		sourceColumn: Đường vào

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số phòng ngủ'
		dataType: double
		lineageTag: c74c73c8-557e-4f84-9916-892d5fdb6464
		summarizeBy: sum
		sourceColumn: Số phòng ngủ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số phòng tắm, vệ sinh'
		dataType: double
		lineageTag: 33e1120c-f1cc-4201-9388-5a4cc33c3f33
		summarizeBy: sum
		sourceColumn: Số phòng tắm, vệ sinh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số tầng'
		dataType: int64
		formatString: 0
		lineageTag: cc21e775-60da-4b69-90c8-3d523a49dc45
		summarizeBy: sum
		sourceColumn: Số tầng

		annotation SummarizationSetBy = Automatic

	column 'Hướng nhà'
		dataType: string
		lineageTag: 7d3a370a-dbb0-4c87-a4bf-45d05ab48123
		summarizeBy: none
		sourceColumn: Hướng nhà

		annotation SummarizationSetBy = Automatic

	column 'Nội thất'
		dataType: string
		lineageTag: a359b07d-e67c-40a7-8e42-e71984589bc5
		summarizeBy: none
		sourceColumn: Nội thất

		annotation SummarizationSetBy = Automatic

	column 'Pháp lý'
		dataType: string
		lineageTag: 32d96b28-d882-488c-93e8-6d1c89900a0c
		summarizeBy: none
		sourceColumn: Pháp lý

		annotation SummarizationSetBy = Automatic

	column 'Loại tin'
		dataType: string
		lineageTag: e368ba7f-efb7-472c-8305-15358264ffe1
		summarizeBy: none
		sourceColumn: Loại tin

		annotation SummarizationSetBy = Automatic

	column 'Biến động giá'
		dataType: double
		lineageTag: f0221bc6-b12a-4468-9d1b-f9a244c0dcd9
		summarizeBy: sum
		sourceColumn: Biến động giá

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Có thang máy'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c0627ccd-b3a7-4935-a039-4f197cef526b
		summarizeBy: none
		sourceColumn: Có thang máy

		annotation SummarizationSetBy = Automatic

	column 'Gần công viên'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dedd8c5d-bfb3-4a97-a6e0-6cdf93b975b9
		summarizeBy: none
		sourceColumn: Gần công viên

		annotation SummarizationSetBy = Automatic

	column 'Mô tả'
		dataType: string
		lineageTag: 5def3e82-ad59-47e8-b7d6-91344bf43151
		summarizeBy: none
		sourceColumn: Mô tả

		annotation SummarizationSetBy = Automatic

	column 'Ngày đăng'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2116bcba-0a61-4a0e-876b-9f35724c7fda
		summarizeBy: none
		sourceColumn: Ngày đăng

		variation Variation
			isDefault
			relationship: 0c1bc912-bc50-4b4d-93bd-5ad7234ffbc0
			defaultHierarchy: LocalDateTable_7478aafa-aae9-4eb5-8c25-cc4601a578b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Đơn giá'
		dataType: double
		lineageTag: 70a130ef-cddc-4e69-9868-5ab330e1288f
		summarizeBy: sum
		sourceColumn: Đơn giá

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Phân loại Đường'
		dataType: string
		lineageTag: d236c1f2-aece-4a3f-96ea-0a3d05a6148c
		summarizeBy: none
		sourceColumn: Phân loại Đường

		annotation SummarizationSetBy = Automatic

	column 'Loại Mặt tiền'
		dataType: string
		lineageTag: 5a4e574a-f649-4c19-bb7a-46dab9dbaff2
		summarizeBy: none
		sourceColumn: Loại Mặt tiền

		annotation SummarizationSetBy = Automatic

	column 'Xu hướng giá'
		dataType: string
		lineageTag: f4ed4341-a051-45bd-a7b9-45796afbae15
		summarizeBy: none
		sourceColumn: Xu hướng giá

		annotation SummarizationSetBy = Automatic

	column 'Loại hình BĐS'
		dataType: string
		lineageTag: df10b522-248f-4e19-a3d1-e73976501f22
		summarizeBy: none
		sourceColumn: Loại hình BĐS

		annotation SummarizationSetBy = Automatic

	column 'Pháp lý Chuẩn hóa'
		dataType: string
		lineageTag: 3ec01539-5242-4a7e-bc5c-b0411365f7e3
		summarizeBy: none
		sourceColumn: Pháp lý Chuẩn hóa

		annotation SummarizationSetBy = Automatic

	column 'Độ dài mô tả'
		dataType: int64
		formatString: 0
		lineageTag: 7ba4f6ae-b6c3-467e-a1ca-dbc683019ce4
		summarizeBy: none
		sourceColumn: Độ dài mô tả

		annotation SummarizationSetBy = Automatic

	column 'Số dấu chấm than'
		dataType: int64
		formatString: 0
		lineageTag: 7171457f-df70-46af-8eb3-027227813657
		summarizeBy: none
		sourceColumn: Số dấu chấm than

		annotation SummarizationSetBy = Automatic

	column 'Tỷ lệ chữ in hoa'
		dataType: double
		lineageTag: e3625fbb-2cc9-4129-b4b5-a2dcb2e48f7d
		summarizeBy: none
		sourceColumn: Tỷ lệ chữ in hoa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column desc_lower
		dataType: string
		lineageTag: 4131871b-2343-497c-9125-946c65027e2c
		summarizeBy: none
		sourceColumn: desc_lower

		annotation SummarizationSetBy = Automatic

	column 'Có dấu hiệu bán gấp'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e4af66a8-e443-47af-a096-3b15233c3e59
		summarizeBy: none
		sourceColumn: Có dấu hiệu bán gấp

		annotation SummarizationSetBy = Automatic

	column 'Có từ khóa marketing'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a731acc4-67a6-4557-852b-80b50959a3ab
		summarizeBy: none
		sourceColumn: Có từ khóa marketing

		annotation SummarizationSetBy = Automatic

	column 'Có từ khóa dòng tiền'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d8d54b33-749b-4613-977c-5bdcf116e3ce
		summarizeBy: none
		sourceColumn: Có từ khóa dòng tiền

		annotation SummarizationSetBy = Automatic

	column 'Có dấu hiệu pháp lý yếu'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dda9dd48-c507-482d-baf7-e89be9e243c5
		summarizeBy: none
		sourceColumn: Có dấu hiệu pháp lý yếu

		annotation SummarizationSetBy = Automatic

	partition Fact_Listings = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Duplicates" = Table.Distinct(Source, {"product_id", "Ngày đăng"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}, Dim_Location, {"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}, "Dim_Location", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"Có thang máy", "Gần công viên", "Có dấu hiệu bán gấp", "Có từ khóa marketing", "Có từ khóa dòng tiền", "Có dấu hiệu pháp lý yếu"}, Dim_Features, {"Có thang máy", "Gần công viên", "Có dấu hiệu bán gấp", "Có từ khóa marketing", "Có từ khóa dòng tiền", "Có dấu hiệu pháp lý yếu"}, "Dim_Features", JoinKind.LeftOuter),
				    #"Merged Queries2" = Table.NestedJoin(#"Merged Queries1", {"Hướng nhà", "Nội thất", "Pháp lý", "Loại tin"}, Dim_Property_Details, {"Hướng nhà", "Nội thất", "Pháp lý", "Loại tin"}, "Dim_Property_Details", JoinKind.LeftOuter),
				    #"Merged Queries3" = Table.NestedJoin(#"Merged Queries2", {"product_id"}, Dim_Product, {"product_id"}, "Dim_Product", JoinKind.LeftOuter),
				    #"Expanded Dim_Location" = Table.ExpandTableColumn(#"Merged Queries3", "Dim_Location", {"Location_SKey"}, {"Location_SKey"}),
				    #"Expanded Dim_Features" = Table.ExpandTableColumn(#"Expanded Dim_Location", "Dim_Features", {"Feature_SKey"}, {"Feature_SKey"}),
				    #"Expanded Dim_Property_Details" = Table.ExpandTableColumn(#"Expanded Dim_Features", "Dim_Property_Details", {"Status_SKey"}, {"Status_SKey"}),
				    #"Expanded Dim_Product" = Table.ExpandTableColumn(#"Expanded Dim_Property_Details", "Dim_Product", {"Product_SKey"}, {"Product_SKey"})
				in
				    #"Expanded Dim_Product"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

