table Fact_Listings
	lineageTag: 6dbf4d8b-6450-49d9-a197-1bfe46312350

	column expiry_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7d6de7f-603e-48ac-8f26-fdce5fac2193
		summarizeBy: none
		sourceColumn: expiry_date

		variation Variation
			isDefault
			relationship: c1dda36e-3c20-4b50-8efd-d85df39eb2b3
			defaultHierarchy: LocalDateTable_4275abd7-7c0a-44cc-993a-521f5c6f11de.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Location_SKey
		dataType: int64
		formatString: 0
		lineageTag: 8eb85d28-0efa-49e7-9036-739ea7fcbf77
		summarizeBy: none
		sourceColumn: Location_SKey

		annotation SummarizationSetBy = Automatic

	column Feature_SKey
		dataType: int64
		formatString: 0
		lineageTag: 3c399081-33a6-4d15-b65d-c54843c31f0b
		summarizeBy: none
		sourceColumn: Feature_SKey

		annotation SummarizationSetBy = Automatic

	column Status_SKey
		dataType: int64
		formatString: 0
		lineageTag: 95d8cd6d-d25e-4a4c-bf40-0e9993a3c007
		summarizeBy: none
		sourceColumn: Status_SKey

		annotation SummarizationSetBy = Automatic

	column Product_SKey
		dataType: int64
		formatString: 0
		lineageTag: 41b238fa-ed81-41e6-9589-8f0722c103cd
		summarizeBy: none
		sourceColumn: Product_SKey

		annotation SummarizationSetBy = Automatic

	column 'Khoảng giá'
		dataType: int64
		formatString: 0
		lineageTag: 10ba38ee-e25e-4078-bc51-e723929c7cb8
		summarizeBy: sum
		sourceColumn: Khoảng giá

		annotation SummarizationSetBy = Automatic

	column 'Diện tích'
		dataType: double
		lineageTag: 5a749730-4dad-4b19-a63e-d2aa2babe48f
		summarizeBy: sum
		sourceColumn: Diện tích

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mặt tiền'
		dataType: double
		lineageTag: cb21897e-4a1d-40f4-a9cd-77406d0fefa4
		summarizeBy: sum
		sourceColumn: Mặt tiền

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Đường vào'
		dataType: double
		lineageTag: f1509322-b72a-4d5f-bf61-c8c0c3ea661b
		summarizeBy: sum
		sourceColumn: Đường vào

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số phòng ngủ'
		dataType: double
		lineageTag: c74c73c8-557e-4f84-9916-892d5fdb6464
		summarizeBy: sum
		sourceColumn: Số phòng ngủ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số phòng tắm, vệ sinh'
		dataType: double
		lineageTag: 33e1120c-f1cc-4201-9388-5a4cc33c3f33
		summarizeBy: sum
		sourceColumn: Số phòng tắm, vệ sinh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số tầng'
		dataType: int64
		formatString: 0
		lineageTag: cc21e775-60da-4b69-90c8-3d523a49dc45
		summarizeBy: sum
		sourceColumn: Số tầng

		annotation SummarizationSetBy = Automatic

	column 'Biến động giá'
		dataType: double
		lineageTag: f0221bc6-b12a-4468-9d1b-f9a244c0dcd9
		summarizeBy: sum
		sourceColumn: Biến động giá

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ngày đăng'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2116bcba-0a61-4a0e-876b-9f35724c7fda
		summarizeBy: none
		sourceColumn: Ngày đăng

		variation Variation
			isDefault
			relationship: 0c1bc912-bc50-4b4d-93bd-5ad7234ffbc0
			defaultHierarchy: LocalDateTable_7478aafa-aae9-4eb5-8c25-cc4601a578b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Đơn giá'
		dataType: double
		lineageTag: 70a130ef-cddc-4e69-9868-5ab330e1288f
		summarizeBy: sum
		sourceColumn: Đơn giá

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Phân loại Đường'
		dataType: string
		lineageTag: d236c1f2-aece-4a3f-96ea-0a3d05a6148c
		summarizeBy: none
		sourceColumn: Phân loại Đường

		annotation SummarizationSetBy = Automatic

	column 'Loại Mặt tiền'
		dataType: string
		lineageTag: 5a4e574a-f649-4c19-bb7a-46dab9dbaff2
		summarizeBy: none
		sourceColumn: Loại Mặt tiền

		annotation SummarizationSetBy = Automatic

	column 'Xu hướng giá'
		dataType: string
		lineageTag: f4ed4341-a051-45bd-a7b9-45796afbae15
		summarizeBy: none
		sourceColumn: Xu hướng giá

		annotation SummarizationSetBy = Automatic

	column 'Loại hình BĐS'
		dataType: string
		lineageTag: df10b522-248f-4e19-a3d1-e73976501f22
		summarizeBy: none
		sourceColumn: Loại hình BĐS

		annotation SummarizationSetBy = Automatic

	partition Fact_Listings = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Duplicates" = Table.Distinct(Source, {"product_id", "Ngày đăng"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}, Dim_Location, {"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}, "Dim_Location", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"Có thang máy", "Gần công viên", "Có dấu hiệu bán gấp", "Có từ khóa marketing", "Có từ khóa dòng tiền", "Có dấu hiệu pháp lý yếu"}, Dim_Features, {"Có thang máy", "Gần công viên", "Có dấu hiệu bán gấp", "Có từ khóa marketing", "Có từ khóa dòng tiền", "Có dấu hiệu pháp lý yếu"}, "Dim_Features", JoinKind.LeftOuter),
				    #"Merged Queries2" = Table.NestedJoin(#"Merged Queries1", {"Hướng nhà", "Nội thất", "Pháp lý", "Loại tin"}, Dim_Property_Details, {"Hướng nhà", "Nội thất", "Pháp lý", "Loại tin"}, "Dim_Property_Details", JoinKind.LeftOuter),
				    #"Merged Queries3" = Table.NestedJoin(#"Merged Queries2", {"product_id"}, Dim_Product, {"product_id"}, "Dim_Product", JoinKind.LeftOuter),
				    #"Expanded Dim_Location" = Table.ExpandTableColumn(#"Merged Queries3", "Dim_Location", {"Location_SKey"}, {"Location_SKey"}),
				    #"Expanded Dim_Features" = Table.ExpandTableColumn(#"Expanded Dim_Location", "Dim_Features", {"Feature_SKey"}, {"Feature_SKey"}),
				    #"Expanded Dim_Property_Details" = Table.ExpandTableColumn(#"Expanded Dim_Features", "Dim_Property_Details", {"Status_SKey"}, {"Status_SKey"}),
				    #"Expanded Dim_Product" = Table.ExpandTableColumn(#"Expanded Dim_Property_Details", "Dim_Product", {"Product_SKey"}, {"Product_SKey"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded Dim_Product",{"Khoảng giá", "Diện tích", "Đơn giá", "Loại hình BĐS", "Mặt tiền", "Loại Mặt tiền", "Đường vào", "Phân loại Đường", "Số phòng ngủ", "Số phòng tắm, vệ sinh", "Số tầng", "Biến động giá", "Xu hướng giá", "Ngày đăng", "expiry_date", "Location_SKey", "Feature_SKey", "Status_SKey", "Product_SKey"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

