table Fact_Listings
	lineageTag: 6dbf4d8b-6450-49d9-a197-1bfe46312350

	measure 'Số tin đăng' = DISTINCTCOUNT('Fact_Listings'[Product_SKey])
		formatString: 0
		lineageTag: e15f350a-9647-4843-9040-c0148e055b39

	measure 'Điểm đỉnh' =
			
			VAR MaxSoTin =
			    MAXX(
			        ALLSELECTED('Fact_Listings'[Khoảng giá bán]),
			        [Số tin đăng]
			    )
			RETURN
			    IF([Số tin đăng] = MaxSoTin, [Số tin đăng], BLANK())
		formatString: 0
		lineageTag: d778376d-fec1-49f4-9d90-85d142246f83

	measure 'Vùng giá có nhiều tin nhất' =
			
			VAR BangTam =
			    ADDCOLUMNS(
			        ALLSELECTED('Fact_Listings'[Khoảng giá bán]),
			        "SoTin", [Số tin đăng]
			    )
			VAR DongCaoNhat =
			    TOPN(
			        1,
			        BangTam,
			        [SoTin],
			        DESC
			    )
			RETURN
			    CONCATENATEX(
			        DongCaoNhat,
			        'Fact_Listings'[Khoảng giá bán],
			        ", "
			    )
		lineageTag: c6fbed4a-a131-4bc4-bb3f-9784788ac6cb

	measure 'Ngưỡng rẻ bất thường' =
			
			PERCENTILEX.INC(
			    ALLSELECTED('Fact_Listings'),
			    'Fact_Listings'[Đơn giá],
			    0.05
			)
		lineageTag: 7b6faa7c-e6c9-4b17-a027-a3fa9dd305eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Số tin rẻ bất thường' =
			
			CALCULATE(
			    [Số tin đăng],
			    FILTER(
			        ALLSELECTED('Fact_Listings'),
			        'Fact_Listings'[Đơn giá] <= [Ngưỡng rẻ bất thường]
			    )
			)
		formatString: 0
		lineageTag: 11001b22-e2f3-45fd-a729-108926e0bd92

	measure '% tin rẻ bất thường' =
			
			DIVIDE(
			    [Số tin rẻ bất thường],
			    [Số tin đăng]
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d9812020-6fa3-4bd1-988d-c2fc42fc4fde

	measure '% Sổ hồng' =
			
			DIVIDE(
			    CALCULATE(COUNT('Fact_Listings'[Product_SKey]), 'Dim_Property_Details'[Pháp lý Chuẩn hóa] = "Sổ hồng/Sổ đỏ"),
			    COUNT('Fact_Listings'[Product_SKey]),
			    0
			)
		lineageTag: 78235c3e-e75f-4a2a-89ce-48af9b7832d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Đơn giá TB Loại BĐS này' = CALCULATE(AVERAGE(Fact_Listings[Đơn giá]), ALLEXCEPT(Fact_Listings, Fact_Listings[Loại hình BĐS]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ee9a8b3a-5683-405e-bdff-7cec040765d6

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column expiry_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7d6de7f-603e-48ac-8f26-fdce5fac2193
		summarizeBy: none
		sourceColumn: expiry_date

		variation Variation
			isDefault
			relationship: c1dda36e-3c20-4b50-8efd-d85df39eb2b3
			defaultHierarchy: LocalDateTable_4275abd7-7c0a-44cc-993a-521f5c6f11de.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Location_SKey
		dataType: int64
		formatString: 0
		lineageTag: 8eb85d28-0efa-49e7-9036-739ea7fcbf77
		summarizeBy: none
		sourceColumn: Location_SKey

		annotation SummarizationSetBy = Automatic

	column Feature_SKey
		dataType: int64
		formatString: 0
		lineageTag: 3c399081-33a6-4d15-b65d-c54843c31f0b
		summarizeBy: none
		sourceColumn: Feature_SKey

		annotation SummarizationSetBy = Automatic

	column Status_SKey
		dataType: int64
		formatString: 0
		lineageTag: 95d8cd6d-d25e-4a4c-bf40-0e9993a3c007
		summarizeBy: none
		sourceColumn: Status_SKey

		annotation SummarizationSetBy = Automatic

	column Product_SKey
		dataType: int64
		formatString: 0
		lineageTag: 41b238fa-ed81-41e6-9589-8f0722c103cd
		summarizeBy: none
		sourceColumn: Product_SKey

		annotation SummarizationSetBy = Automatic

	column 'Khoảng giá'
		dataType: decimal
		formatString: #,0
		lineageTag: 10ba38ee-e25e-4078-bc51-e723929c7cb8
		summarizeBy: sum
		sourceColumn: Khoảng giá

		annotation SummarizationSetBy = Automatic

	column 'Diện tích'
		dataType: double
		lineageTag: 5a749730-4dad-4b19-a63e-d2aa2babe48f
		summarizeBy: sum
		sourceColumn: Diện tích

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Fact_Listings","TableItemName":"Diện tích (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Mặt tiền'
		dataType: double
		lineageTag: cb21897e-4a1d-40f4-a9cd-77406d0fefa4
		summarizeBy: sum
		sourceColumn: Mặt tiền

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Đường vào'
		dataType: double
		lineageTag: f1509322-b72a-4d5f-bf61-c8c0c3ea661b
		summarizeBy: sum
		sourceColumn: Đường vào

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số phòng ngủ'
		dataType: double
		lineageTag: c74c73c8-557e-4f84-9916-892d5fdb6464
		summarizeBy: sum
		sourceColumn: Số phòng ngủ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số phòng tắm, vệ sinh'
		dataType: double
		lineageTag: 33e1120c-f1cc-4201-9388-5a4cc33c3f33
		summarizeBy: sum
		sourceColumn: Số phòng tắm, vệ sinh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Số tầng'
		dataType: int64
		formatString: 0
		lineageTag: cc21e775-60da-4b69-90c8-3d523a49dc45
		summarizeBy: sum
		sourceColumn: Số tầng

		annotation SummarizationSetBy = Automatic

	column 'Biến động giá'
		dataType: double
		lineageTag: f0221bc6-b12a-4468-9d1b-f9a244c0dcd9
		summarizeBy: sum
		sourceColumn: Biến động giá

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ngày đăng'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2116bcba-0a61-4a0e-876b-9f35724c7fda
		summarizeBy: none
		sourceColumn: Ngày đăng

		variation Variation
			isDefault
			relationship: 0c1bc912-bc50-4b4d-93bd-5ad7234ffbc0
			defaultHierarchy: LocalDateTable_7478aafa-aae9-4eb5-8c25-cc4601a578b2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Đơn giá'
		dataType: decimal
		formatString: #,0.00
		lineageTag: df38144f-a43b-4cc5-b25a-253daa230f6f
		summarizeBy: sum
		sourceColumn: Đơn giá

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Fact_Listings","TableItemName":"Khoảng đơn giá/m²","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Fact_Listings","TableItemName":"Đơn giá (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Phân loại Đường'
		dataType: string
		lineageTag: d236c1f2-aece-4a3f-96ea-0a3d05a6148c
		summarizeBy: none
		sourceColumn: Phân loại Đường

		annotation SummarizationSetBy = Automatic

	column 'Loại Mặt tiền'
		dataType: string
		lineageTag: 5a4e574a-f649-4c19-bb7a-46dab9dbaff2
		summarizeBy: none
		sourceColumn: Loại Mặt tiền

		annotation SummarizationSetBy = Automatic

	column 'Xu hướng giá'
		dataType: string
		lineageTag: f4ed4341-a051-45bd-a7b9-45796afbae15
		summarizeBy: none
		sourceColumn: Xu hướng giá

		annotation SummarizationSetBy = Automatic

	column 'Loại hình BĐS'
		dataType: string
		lineageTag: df10b522-248f-4e19-a3d1-e73976501f22
		summarizeBy: none
		sourceColumn: Loại hình BĐS

		annotation SummarizationSetBy = Automatic

	column Is_Overcrowded
		dataType: boolean
		lineageTag: e8d29b2b-42fa-4a25-a1c2-555a123b3210
		summarizeBy: none
		sourceColumn: Is_Overcrowded

		annotation SummarizationSetBy = Automatic

	column Is_Fire_Risk
		dataType: boolean
		lineageTag: e8d29b2b-42fa-4a25-a1c2-555a123b3211
		summarizeBy: none
		sourceColumn: Is_Fire_Risk

		annotation SummarizationSetBy = Automatic

	column 'Giá bán (tỷ đồng)' = [Khoảng giá] / 1000
		formatString: #,0.00
		lineageTag: da9d8c65-34b4-466a-a6a8-3a9a5d841806
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Fact_Listings","TableItemName":"Khoảng giá bán","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Khoảng giá bán' =
			IF(
				ISBLANK('Fact_Listings'[Giá bán (tỷ đồng)]),
				BLANK(),
				INT('Fact_Listings'[Giá bán (tỷ đồng)] / 0.5) * 0.5
			)
		formatString: #,0.00
		lineageTag: 44f3606f-47bd-4b59-8043-eced1eec11ab
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Fact_Listings"
				          }
				        },
				        "Property": "Giá bán (tỷ đồng)"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 0.5,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"Fact_Listings"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Giá bán (tỷ đồng)"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Giá bán (tỷ đồng)"}},"Size":0.5}}}}

		annotation SummarizationSetBy = Automatic

	column 'Khoảng đơn giá/m²' =
			IF(
				ISBLANK('Fact_Listings'[Đơn giá]),
				BLANK(),
				INT('Fact_Listings'[Đơn giá] / 5) * 5
			)
		formatString: #,0.00
		lineageTag: d1307432-4440-42a8-8972-92439a23c6bc
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Fact_Listings"
				          }
				        },
				        "Property": "Đơn giá"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 5.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"Fact_Listings"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Đơn giá"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Đơn giá"}},"Size":5.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Tỷ lệ sâu/rộng' = ```
			
			DIVIDE(
			    'Fact_Listings'[Diện tích],
			    'Fact_Listings'[Mặt tiền] * 'Fact_Listings'[Mặt tiền] 
			)
			```
		lineageTag: 61fcde6b-8556-4f33-9ecf-2ecacd406db3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Nhóm hình dáng thửa đất' =
			
			VAR TyLe =
			    DIVIDE(
			        'Fact_Listings'[Diện tích],
			        'Fact_Listings'[Mặt tiền] * 'Fact_Listings'[Mặt tiền]
			    )
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK('Fact_Listings'[Mặt tiền]) || ISBLANK('Fact_Listings'[Mặt tiền]), "Thiếu thông tin",
			        TyLe < 1.5, "Mặt tiền rộng",
			        TyLe < 3, "Cân đối",
			        TyLe < 5, "Nhà hẹp dài",
			        "Ống siêu dài"
			    )
		lineageTag: 945d6bae-2123-44bb-abc0-8f33c5c78492
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PhanKhuc =
			
			// Bước 1: Tính các mốc bách phân vị dựa trên TOÀN BỘ dữ liệu và LÀM TRÒN
			VAR MocBinhDan = ROUND(CALCULATE(PERCENTILE.INC('Fact_Listings'[Khoảng giá], 0.25), ALL('Fact_Listings')), 0)
			VAR MocCaoCap = ROUND(CALCULATE(PERCENTILE.INC('Fact_Listings'[Khoảng giá], 0.75), ALL('Fact_Listings')), 0)
			
			// Bước 2: Phân loại
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK('Fact_Listings'[Khoảng giá]), "Không xác định",
			    'Fact_Listings'[Khoảng giá] <= MocBinhDan, "Bình dân",
			    'Fact_Listings'[Khoảng giá] <= MocCaoCap, "Trung bình",
			    "Cao cấp"
			)
		lineageTag: 90bfd98b-e4d0-4b17-9c66-b76cfa9322df
		summarizeBy: none
		sortByColumn: PhanKhuc_SapXep

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column PhanKhuc_SapXep =
			
			VAR MocBinhDan = CALCULATE(PERCENTILE.INC('Fact_Listings'[Khoảng giá], 0.25), ALL('Fact_Listings'))
			VAR MocCaoCap = CALCULATE(PERCENTILE.INC('Fact_Listings'[Khoảng giá], 0.75), ALL('Fact_Listings'))
			
			RETURN
			SWITCH(
			    TRUE(),
			    ISBLANK('Fact_Listings'[Khoảng giá]), 4,
			    'Fact_Listings'[Khoảng giá] <= MocBinhDan, 1,
			    'Fact_Listings'[Khoảng giá] <= MocCaoCap, 2,
			    3
			)
		formatString: 0
		lineageTag: b3cdbcdc-aaf7-418b-b348-0f38e3ee5bd4

	column So_Ngay_Hien_Thi = DATEDIFF('Fact_Listings'[Ngày đăng], 'Fact_Listings'[expiry_date], DAY)
		formatString: 0
		lineageTag: 47401535-5f3a-4a4f-b794-5266d6f2092e
		summarizeBy: sum

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Listing_ID
		dataType: int64
		formatString: 0
		lineageTag: b6f81f75-080f-49b1-ad8f-baaecbda785a
		summarizeBy: count
		sourceColumn: Listing_ID

		annotation SummarizationSetBy = Automatic

	column Nhom_Chat_Luong_Thocu = ```
			
			VAR MatTien = 'Fact_Listings'[Loại Mặt tiền]
			VAR Duong = 'Fact_Listings'[Phân loại Đường]
			VAR PhapLy = RELATED('Dim_Property_Details'[Pháp lý Chuẩn hóa (groups)])
			
			VAR MatTienTot = MatTien IN {"Khá (5-10m)", "Rất rộng (>10m)"}
			VAR DuongTot = Duong IN {"Đường xe hơi (5-10m)", "Đường lớn (>10m)"}
			
			VAR PhapLyManh = PhapLy = "Sổ hồng/Sổ đỏ"
			VAR PhapLyYeu = PhapLy IN {"Chưa xác định & Hợp đồng mua bán", "Sổ chung"}
			
			VAR ViTriKem = NOT(MatTienTot) && NOT(DuongTot)
			
			RETURN
			SWITCH(
			    TRUE(),
			    // Tầng 1: Đáy rủi ro
			    PhapLyYeu && ViTriKem, "Rủi ro kép (Pháp lý yếu + Hẻm nhỏ)",
			    
			    // Tầng 2: Cạm bẫy lùa gà mặt tiền
			    PhapLyYeu, "Rủi ro ngầm (Pháp lý yếu + Vị trí trung bình/đẹp)",
			    
			    // Tầng 3: Hàng Hiệu
			    PhapLyManh && (MatTienTot || DuongTot), "Cao cấp (Sổ đỏ + Mặt tiền/Đường lớn)",
			    
			    // Tầng 4: Hàng ở thực an toàn (Khóa chặt: Phải CÓ SỔ mới được vào nhóm này)
			    PhapLyManh, "Phổ thông (Sổ đỏ + Nhà hẻm)",
			    
			    // Tầng 5: Lưới an toàn (Bắt hết các ca Blank/Lỗi gõ phím để dữ liệu luôn sạch 100%)
			    "Khác (Dữ liệu chưa xác định)"
			)
			```
		lineageTag: c7de3787-2be7-4d44-90e5-272a4cc82d2c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Đơn giá (bins)' =
			IF(
				ISBLANK('Fact_Listings'[Đơn giá]),
				BLANK(),
				INT('Fact_Listings'[Đơn giá] / 2) * 2
			)
		formatString: #,0.00
		lineageTag: f9d6e5a9-1925-4210-b6f2-1eb65f5333ed
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Fact_Listings"
				          }
				        },
				        "Property": "Đơn giá"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 2.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"Fact_Listings"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Đơn giá"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Đơn giá"}},"Size":2.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Diện tích (bins)' =
			IF(
				ISBLANK('Fact_Listings'[Diện tích]),
				BLANK(),
				IF(
					'Fact_Listings'[Diện tích] >= 0,
					ROUNDDOWN('Fact_Listings'[Diện tích] / 50, 0) * 50,
					ROUNDUP('Fact_Listings'[Diện tích] / 50, 0) * 50
				)
			)
		lineageTag: a4cfb452-2419-4475-b805-778ad83287fc
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Fact_Listings"
				          }
				        },
				        "Property": "Diện tích"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 50.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"Fact_Listings"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Diện tích"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Diện tích"}},"Size":50.0}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Listings = m
		mode: import
		source =
				let
				    Source = batdongsan_real_estate_cleaned,
				    #"Removed Duplicates" = Table.Distinct(Source, {"product_id", "Ngày đăng"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Duplicates", {"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}, Dim_Location, {"Thành phố", "Quận", "Phường", "Đường", "Địa chỉ"}, "Dim_Location", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"Có thang máy", "Gần công viên", "Có dấu hiệu bán gấp", "Có từ khóa marketing", "Có từ khóa dòng tiền", "Có dấu hiệu pháp lý yếu"}, Dim_Features, {"Có thang máy", "Gần công viên", "Có dấu hiệu bán gấp", "Có từ khóa marketing", "Có từ khóa dòng tiền", "Có dấu hiệu pháp lý yếu"}, "Dim_Features", JoinKind.LeftOuter),
				    #"Merged Queries2" = Table.NestedJoin(#"Merged Queries1", {"Hướng nhà", "Nội thất", "Pháp lý", "Loại tin"}, Dim_Property_Details, {"Hướng nhà", "Nội thất", "Pháp lý", "Loại tin"}, "Dim_Property_Details", JoinKind.LeftOuter),
				    #"Merged Queries3" = Table.NestedJoin(#"Merged Queries2", {"product_id"}, Dim_Product, {"product_id"}, "Dim_Product", JoinKind.LeftOuter),
				    #"Expanded Dim_Location" = Table.ExpandTableColumn(#"Merged Queries3", "Dim_Location", {"Location_SKey"}, {"Location_SKey"}),
				    #"Expanded Dim_Features" = Table.ExpandTableColumn(#"Expanded Dim_Location", "Dim_Features", {"Feature_SKey"}, {"Feature_SKey"}),
				    #"Expanded Dim_Property_Details" = Table.ExpandTableColumn(#"Expanded Dim_Features", "Dim_Property_Details", {"Status_SKey"}, {"Status_SKey"}),
				    #"Expanded Dim_Product" = Table.ExpandTableColumn(#"Expanded Dim_Property_Details", "Dim_Product", {"Product_SKey"}, {"Product_SKey"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded Dim_Product", {"Khoảng giá", "Diện tích", "Đơn giá", "Loại hình BĐS", "Mặt tiền", "Loại Mặt tiền", "Đường vào", "Phân loại Đường", "Số phòng ngủ", "Số phòng tắm, vệ sinh", "Số tầng", "Biến động giá", "Xu hướng giá", "Ngày đăng", "expiry_date", "Location_SKey", "Feature_SKey", "Status_SKey", "Product_SKey"}),
				    #"Added Is_Overcrowded" = Table.AddColumn(#"Removed Other Columns", "Is_Overcrowded", each if [Diện tích] <> null and [Số phòng ngủ] <> null and [Diện tích] < 40 and [Số phòng ngủ] >= 3 then true else false, type logical),
				    #"Added Is_Fire_Risk" = Table.AddColumn(#"Added Is_Overcrowded", "Is_Fire_Risk", each if [Số tầng] <> null and [Đường vào] <> null and [Số tầng] > 5 and [Đường vào] < 3 then true else false, type logical),
				    #"Added Index" = Table.AddIndexColumn(#"Added Is_Fire_Risk", "Listing_ID", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

